from symtable import Class

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import math
from torch import dtype, nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
import os
from pathlib import Path
from tqdm import tqdm
from scipy.interpolate import CubicSpline



SCRIPT_DIR = Path(__file__).resolve().parent
CHECKPOINT_DIR = SCRIPT_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(exist_ok=True)
PLOT_DIR = SCRIPT_DIR / "plots"
PLOT_DIR.mkdir(exist_ok=True)

"""
HOW TO RUN THIS FILE:

This file contains all: Dataloading, model definition and the training loop. Sampling functions are also included to generate trajectories from the trained model.

The forward process initially takes samples from the training data, and adds noise to control waypoints discretely over T = 200 steps.

The model is then trained to output the amount of noise to remove from a set of control waypoints, based on environmental conditions: Map Mean, Map Variance, and Current position. 

The reverse sampling process starts from pure np.random noise, and iteratively denoises according to the DDIM sampling scheme, to produce control waypoints that best fit the current situation.

Hyperparams that affect training and sampling are defined at the top of the file: 
EPOCHS, BATCH_SIZE, LR, and INDEX (for debugging with a smaller subset of the data).

Conditioning and Model details:
MeanVarMarkerCNN takes in a 3-channel map of shape (B, 3, 51, 51) [batch, map data, x, y], where the 3 channels are: Mean map, Variance map, and a one-hot marker for the current position.
The CNN processes this map to extract spatial features that help the model understand the environment and how it relates to the control waypoints.

In NoisePredictor(), the time embedding and the mean-var-marker map embedding are combined to create a conditioning vector that modulates the convolutional blocks through FiLM-style conditioning.
A U-Net architectue is used here to predict the noise to remove from the input noisy control waypoints. The model outputs a tensor of the same shape as the control waypoints, which represents the predicted noise that should be subtracted to denoise the waypoints.


Training: 
Train() runs the loop over all training data that fit in the index range. The flow is: 
- Forward process picks a random timestep and corrupts a sample of waypoints corresponding to that timestep with noise.
- The model then takes in the noisy waypoints, the conditioning map, and the current position, and tries to predict the noise that was added.
- The loss is a combination of the MSE between the predicted noise and the true noise at the waypoint level, plus an additional MSE loss on the dense trajectory generated by applying a cubic spline to the predicted noise and true noise.


- x_0: one sample is shaped (B, 2, 8) [batch, coords, control waypoint columns]
- data: CMAES_classic_beamsearch_dataset.pt
- control waypoints are normalized to [-1, 1]
"""

EPOCHS = 1
BATCH_SIZE = 256
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_COORDS = 2
NUM_CONTROL_WAYPOINTS = 8
TARGET_SHAPE = (NUM_COORDS, NUM_CONTROL_WAYPOINTS)
FLAT_TRAJ_DIM = NUM_COORDS * NUM_CONTROL_WAYPOINTS
LR = 3e-4
WEIGHT_DECAY = 1e-4
GRAD_CLIP_NORM = 1.0
MIN_LR = 1e-5
INDEX = -1



def cosine_beta_schedule(timesteps, s=0.008):
    steps = timesteps + 1
    x = torch.linspace(0, timesteps, steps)
    alphas_cumprod = torch.cos((((x / timesteps) + s) / (1 + s)) * torch.pi * 0.5) ** 2
    alphas_cumprod = alphas_cumprod / alphas_cumprod[0]
    betas = 1 - (alphas_cumprod[1:] / alphas_cumprod[:-1])
    return torch.clamp(betas, 1e-4, 0.05)


def get_index_from_list(vals, t, x_shape):
    batch_size = t.shape[0]
    out = vals.gather(-1, t.cpu())
    return out.reshape(batch_size, *((1,) * (len(x_shape) - 1))).to(t.device)


def forward_diffusion_sample(x_0, t):
    noise = torch.randn_like(x_0)

    sqrt_alphas_cumprod_t = get_index_from_list(sqrt_alphas_cumprod, t, x_0.shape)
    sqrt_one_minus_alphas_cumprod_t = get_index_from_list(sqrt_one_minus_alphas_cumprod, t, x_0.shape)

    x_t = sqrt_alphas_cumprod_t * x_0 + sqrt_one_minus_alphas_cumprod_t * noise
    return x_t, noise


#FORWARD PROCESS HYPERPARAM
T = 70
betas = cosine_beta_schedule(timesteps=T)
alphas = 1.0 - betas
alphas_cumprod = torch.cumprod(alphas, axis=0)
alphas_cumprod_prev = F.pad(alphas_cumprod[:-1], (1, 0), value=1.0)
sqrt_recip_alphas = torch.sqrt(1.0 / alphas)
sqrt_alphas_cumprod = torch.sqrt(alphas_cumprod)
sqrt_one_minus_alphas_cumprod = torch.sqrt(1.0 - alphas_cumprod)
posterior_variance = betas * (1.0 - alphas_cumprod_prev) / (1.0 - alphas_cumprod)


data_dict = torch.load(
    SCRIPT_DIR / "CMAES_currentstack_beamsearch_dataset.pt"
)
dense_trajectories = data_dict["trajectories"].float()
control_waypoints = data_dict["control_waypoints"].float()
raw_current_positions = data_dict["current_position"].float()
conditions = raw_current_positions.clone()


##Conditions Maps: Converting (cx, cy) into a map, for spatial relevance.

empty_map = torch.zeros((1, 51, 51), dtype=torch.float32)

def make_position_marker_maps(positions, grid_size = 51, marker_radius = 2):
    """
    current pos: [B,2] --> map pos one hot encoding [B, 1, 51, 51]
    """

    B = positions.shape[0] 
    marker = torch.zeros((B, 1, grid_size, grid_size), dtype=torch.float32, device = positions.device)


    grid_pos = (positions/ SCALE_FACTOR) * (grid_size - 1)
    grid_pos = grid_pos.round().long().clamp(0, grid_size - 1)

    x_idx = grid_pos[:, 0]
    y_idx = grid_pos[:, 1]

    marker[torch.arange(B), 0, y_idx, x_idx] = 1.0
    return marker




means = data_dict["current_mean"].float()
vars = data_dict["current_var"].float()
rmsedrop = data_dict["RMSE_correction"].float()
map_ids = data_dict["map_id"].long()
timesteps = data_dict["timestep"].long()


weighting_utilities = rmsedrop.clamp_min(0.0) + 1e-6
weights = torch.zeros_like(weighting_utilities)

groups = torch.stack([map_ids, timesteps], dim=1)

for group in torch.unique(groups, dim=0):
    group_mask = (groups == group).all(dim=1)
    group_rmsedrop = weighting_utilities[group_mask]
    denom = group_rmsedrop.sum() + 1e-6

    weights[group_mask] = group_rmsedrop / denom




SCALE_FACTOR = 100.0
one_hot_current_positions = make_position_marker_maps(raw_current_positions, grid_size=51, marker_radius=2)


conditions = (conditions / SCALE_FACTOR) * 2.0 - 1.0

######NORMALIZING AND INDEXING######
if control_waypoints.ndim != 3:
    raise ValueError(f"Expected control_waypoints to be rank 3, got {control_waypoints.shape}")

if control_waypoints.shape[1:] == TARGET_SHAPE:
    trajectories = control_waypoints
elif control_waypoints.shape[1:] == (NUM_CONTROL_WAYPOINTS, NUM_COORDS):
    trajectories = control_waypoints.permute(0, 2, 1)
else:
    raise ValueError(
        "Expected control_waypoints shape [B, 2, 8] or [B, 8, 2], "
        f"got {tuple(control_waypoints.shape)}"
    )

trajectories = (trajectories / SCALE_FACTOR) * 2.0 - 1.0

def denormalize_control_waypoints(waypoints):
    return ((waypoints + 1.0) / 2.0) * SCALE_FACTOR


def extract_control_waypoints(waypoint_tensor):
    return denormalize_control_waypoints(waypoint_tensor)


def pytorch_cubic_spline(control_waypoints, current_position, samples_per_segment=5, eps=1e-9):
    """
    Batched differentiable natural cubic spline.

    Args:
        control_waypoints:
            [B, K, 2] or [B, 2, K] or [K, 2] or [2, K]

        current_position:
            [B, 2] or [2] or flattened [2B]

    Returns:
        dense_path:
            [B, 2, samples_per_segment * K + 1]
    """

    if not torch.is_tensor(control_waypoints):
        control_waypoints = torch.tensor(control_waypoints, dtype=torch.float32)

    device = control_waypoints.device
    dtype = control_waypoints.dtype

    if not torch.is_tensor(current_position):
        current_position = torch.tensor(current_position, dtype=dtype, device=device)

    current_position = current_position.to(device=device, dtype=dtype)

    # -------------------------
    # Normalize control_waypoints to [B, K, 2]
    # -------------------------
    if control_waypoints.ndim == 2:
        # Single sample: [K, 2] or [2, K]
        if control_waypoints.shape[0] == 2 and control_waypoints.shape[1] != 2:
            control_waypoints = control_waypoints.T
        control_waypoints = control_waypoints.unsqueeze(0)  # [1, K, 2]

    elif control_waypoints.ndim == 3:
        # Batched: [B, 2, K] -> [B, K, 2]
        if control_waypoints.shape[1] == 2 and control_waypoints.shape[2] != 2:
            control_waypoints = control_waypoints.transpose(1, 2)

    else:
        raise ValueError(f"control_waypoints must have 2 or 3 dims, got {control_waypoints.shape}")

    B, K, D = control_waypoints.shape

    if D != 2:
        raise ValueError(f"Expected waypoint dimension 2, got shape {control_waypoints.shape}")

    # -------------------------
    # Normalize current_position to [B, 1, 2]
    # -------------------------
    if current_position.ndim == 1:
        if current_position.numel() == 2:
            current_position = current_position.reshape(1, 2).repeat(B, 1)
        elif current_position.numel() == 2 * B:
            current_position = current_position.reshape(B, 2)
        else:
            raise ValueError(
                f"current_position has {current_position.numel()} elements, "
                f"expected 2 or {2 * B}"
            )

    elif current_position.ndim == 2:
        if current_position.shape == (1, 2) and B > 1:
            current_position = current_position.repeat(B, 1)
        elif current_position.shape != (B, 2):
            raise ValueError(
                f"current_position shape {current_position.shape} does not match batch size {B}"
            )

    else:
        raise ValueError(f"current_position must have shape [2], [B,2], or [2B], got {current_position.shape}")

    current_position = current_position.reshape(B, 1, 2)

    # Full waypoint sequence: [B, N, 2], N = K + 1
    waypoints = torch.cat([current_position, control_waypoints], dim=1)

    N = waypoints.shape[1]

    # Segment lengths: [B, N-1]
    deltas = waypoints[:, 1:, :] - waypoints[:, :-1, :]
    h = torch.linalg.norm(deltas, dim=-1).clamp_min(eps)

    # Build batched linear systems A M = rhs
    A = torch.zeros(B, N, N, device=device, dtype=dtype)
    rhs = torch.zeros(B, N, 2, device=device, dtype=dtype)

    # Natural boundary conditions
    A[:, 0, 0] = 1.0
    A[:, -1, -1] = 1.0

    for i in range(1, N - 1):
        h_prev = h[:, i - 1]
        h_next = h[:, i]

        A[:, i, i - 1] = h_prev
        A[:, i, i] = 2.0 * (h_prev + h_next)
        A[:, i, i + 1] = h_next

        slope_next = (waypoints[:, i + 1, :] - waypoints[:, i, :]) / h_next[:, None]
        slope_prev = (waypoints[:, i, :] - waypoints[:, i - 1, :]) / h_prev[:, None]

        rhs[:, i, :] = 6.0 * (slope_next - slope_prev)

    # Second derivatives at knots: [B, N, 2]
    M = torch.linalg.solve(A, rhs)

    trajectory_segments = []

    alphas = torch.linspace(
        0.0,
        1.0,
        samples_per_segment + 1,
        device=device,
        dtype=dtype,
    )[:-1]  # [S_seg]

    for i in range(N - 1):
        hi = h[:, i]  # [B]

        tau = alphas[None, :] * hi[:, None]  # [B, S_seg]

        Acoef = hi[:, None] - tau
        Bcoef = tau

        yi = waypoints[:, i, :]        # [B, 2]
        yi1 = waypoints[:, i + 1, :]   # [B, 2]
        Mi = M[:, i, :]                # [B, 2]
        Mi1 = M[:, i + 1, :]           # [B, 2]

        hi_exp = hi[:, None, None]
        Acoef_exp = Acoef[:, :, None]
        Bcoef_exp = Bcoef[:, :, None]

        points = (
            Mi[:, None, :] * Acoef_exp**3 / (6.0 * hi_exp)
            + Mi1[:, None, :] * Bcoef_exp**3 / (6.0 * hi_exp)
            + (yi - Mi * hi[:, None]**2 / 6.0)[:, None, :] * (Acoef_exp / hi_exp)
            + (yi1 - Mi1 * hi[:, None]**2 / 6.0)[:, None, :] * (Bcoef_exp / hi_exp)
        )

        trajectory_segments.append(points)  # [B, samples_per_segment, 2]

    # Append final waypoint exactly
    trajectory_segments.append(waypoints[:, -1:, :])  # [B, 1, 2]

    dense_path = torch.cat(trajectory_segments, dim=1)  # [B, S, 2]

    return dense_path.transpose(1, 2)  # [B, 2, S]





# def spline_regeneration(sparse_states_generated, samples_per_segment=5):
#     """
#     sparse_states_generated: [2, 9] in world coordinates.
#         column 0 = current position
#         columns 1: = 8 control waypoints

#     returns:
#         dense_path: [2, 41]
#         dense_actions: [2, 40]
#     """
#     waypoints = sparse_states_generated.T  # [9, 2]

#     deltas = np.diff(waypoints, axis=0)
#     seg_lengths = np.hypot(deltas[:, 0], deltas[:, 1])
#     t = np.concatenate([[0.0], np.cumsum(seg_lengths)])

#     keep = np.concatenate([[True], np.diff(t) > 1e-9])
#     waypoints = waypoints[keep]
#     t = t[keep]

#     if len(t) < 2:
#         dense_path = np.repeat(waypoints[:1], 41, axis=0)
#         dense_path = dense_path.T
#         dense_actions = dense_path[:, 1:] - dense_path[:, :-1]
#         return dense_path, dense_actions

#     cs_x = CubicSpline(t, waypoints[:, 0], bc_type="natural")
#     cs_y = CubicSpline(t, waypoints[:, 1], bc_type="natural")

#     trajectory = []
#     for i in range(len(t) - 1):
#         t_segment = np.linspace(t[i], t[i + 1], samples_per_segment, endpoint=False)
#         for ts in t_segment:
#             trajectory.append((float(cs_x(ts)), float(cs_y(ts))))

#     trajectory.append((float(waypoints[-1, 0]), float(waypoints[-1, 1])))

#     dense_path = np.asarray(trajectory, dtype=np.float32).T  # [2, 41]
#     dense_actions = dense_path[:, 1:] - dense_path[:, :-1]  # [2, 40]

#     return dense_path, dense_actions

# The conditioning channels have very different scales. Standardizing the mean
# map and log-variance map makes optimization much easier for the MLP.
# log_vars = torch.log1p(vars)
mean_center = means.mean()
mean_scale = means.std().clamp_min(1e-6)
var_center = vars.mean()
var_scale = vars.std().clamp_min(1e-6)

means = (means - mean_center) / mean_scale
vars = (vars - var_center) / var_scale
meanvarmaps = torch.stack([means, vars], dim=1)  # shape (B, 2, 51, 51)
meanvarmarkermaps = torch.stack([means, vars, one_hot_current_positions.squeeze(1)], dim=1)  # shape (B, 3, 51, 51)


if INDEX is not None and INDEX > 0:
    trajectories = trajectories[:INDEX]
    conditions = conditions[:INDEX]
    means = means[:INDEX]
    vars = vars[:INDEX]
    rmsedrop = rmsedrop[:INDEX]
    weights = weights[:INDEX]
    meanvarmarkermaps = meanvarmarkermaps[:INDEX]
    map_ids = map_ids[:INDEX]
    timesteps = timesteps[:INDEX]


class TrajectoryDataset(Dataset):
    def __init__(self, trajectories, weights, meanvarmarkermaps = meanvarmarkermaps, conditions=None):
        self.trajectories = trajectories
        self.weights = weights
        self.rmsedrop = rmsedrop
        self.conditions = conditions
        self.meanvarmarkermaps = meanvarmarkermaps

    def __len__(self):
        return len(self.trajectories)

    def __getitem__(self, idx):
        if self.conditions is None:
            return self.trajectories[idx]
        return self.trajectories[idx], self.conditions[idx], self.meanvarmarkermaps[idx], self.weights[idx]


def build_map_id_split(val_count=2):
    unique_map_ids = torch.unique(map_ids).sort().values
    if unique_map_ids.numel() <= val_count:
        raise ValueError(
            f"Need more than {val_count} map_ids to build a validation split, got {unique_map_ids.tolist()}"
        )
    val_map_ids = unique_map_ids[-val_count:]
    val_mask = torch.isin(map_ids, val_map_ids)
    train_mask = ~val_mask
    return train_mask, val_mask, val_map_ids




class SpatialSinusoidalPositionEmbeddings2D(nn.Module):
    def __init__(self, dim):
        super().__init__()
        if dim % 4 != 0:
            raise ValueError("2D sin/cos position embedding dim must be divisible by 4")
        self.dim = dim

    def forward(self, height, width, device=None, dtype=None):
        device = device or torch.device("cpu")
        dtype = dtype or torch.float32

        y = torch.linspace(-1.0, 1.0, height, device=device, dtype=dtype)
        x = torch.linspace(-1.0, 1.0, width, device=device, dtype=dtype)
        yy, xx = torch.meshgrid(y, x, indexing="ij")
        positions = torch.stack([xx, yy], dim=-1).reshape(-1, 2)

        half_coord_dim = self.dim // 4
        omega = torch.arange(half_coord_dim, device=device, dtype=dtype)
        omega = 1.0 / (10000 ** (omega / max(half_coord_dim - 1, 1)))

        x_emb = positions[:, 0:1] * omega[None, :]
        y_emb = positions[:, 1:2] * omega[None, :]
        embeddings = torch.cat(
            [x_emb.sin(), x_emb.cos(), y_emb.sin(), y_emb.cos()],
            dim=-1,
        )
        return embeddings.unsqueeze(0)


map_token_set = []


def plot_captured_map_tokens(
    output_path=None,
    max_sets=4,
    sample_index=0,
    channel_indices=(0, 1, 2),
    seed=0,
):
    if not map_token_set:
        print("No captured map tokens to plot.")
        return

    rng = np.random.default_rng(seed)
    num_sets = min(max_sets, len(map_token_set))
    set_indices = rng.choice(len(map_token_set), size=num_sets, replace=False)
    channel_indices = tuple(channel_indices)
    num_cols = 1 + len(channel_indices)

    fig, axes = plt.subplots(
        num_sets,
        num_cols,
        figsize=(3.2 * num_cols, 3.0 * num_sets),
        squeeze=False,
    )

    for row, set_idx in enumerate(set_indices):
        tokens = map_token_set[int(set_idx)]
        if sample_index >= tokens.shape[0]:
            raise ValueError(
                f"sample_index={sample_index} is out of range for captured token batch "
                f"with size {tokens.shape[0]}"
            )

        token_grid = tokens[sample_index]
        grid_side = int(math.sqrt(token_grid.shape[0]))
        if grid_side * grid_side != token_grid.shape[0]:
            raise ValueError(f"Expected square token grid, got {token_grid.shape[0]} tokens")

        norm_img = token_grid.norm(dim=-1).reshape(grid_side, grid_side).numpy()
        ax = axes[row, 0]
        im = ax.imshow(norm_img, origin="lower", cmap="viridis")
        ax.set_title(f"set {int(set_idx)}: token norm")
        ax.set_xticks([])
        ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

        for col, channel_idx in enumerate(channel_indices, start=1):
            if channel_idx >= token_grid.shape[1]:
                raise ValueError(
                    f"channel index {channel_idx} is out of range for token dim {token_grid.shape[1]}"
                )
            channel_img = token_grid[:, channel_idx].reshape(grid_side, grid_side).numpy()
            ax = axes[row, col]
            im = ax.imshow(channel_img, origin="lower", cmap="coolwarm")
            ax.set_title(f"set {int(set_idx)}: channel {channel_idx}")
            ax.set_xticks([])
            ax.set_yticks([])
            fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    if output_path is None:
        output_path = PLOT_DIR / "sparse_trans_map_tokens.png"
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved captured map token plot to {output_path}")
    
 
 
class MeanVarMarkerCNN(nn.Module):
    def __init__(
        self,
        input_channels=3,
        hidden_dim=64,
        token_dim=128,
        output_dim=None,
        pos_hidden_dim=32,
    ):
        super().__init__()
        if output_dim is not None:
            token_dim = output_dim


        """
        input maps: (B, 3, 51, 51) [batch, map data, x, y] (3 channels for mean, var, and marker)
        """

        self.conv1 = nn.Conv2d(in_channels=input_channels, out_channels=hidden_dim, kernel_size=3, padding=1) #(B, 3, 51, 51) -> (B, 64, 51, 51)
        self.act1 = nn.SiLU()
        self.pool1 = nn.MaxPool2d(kernel_size=2) # (B, 64, 51, 51) -> (B, 64, 25, 25)
        self.conv2 = nn.Conv2d(in_channels=hidden_dim, out_channels=hidden_dim * 2, kernel_size=3, padding=1) # (B, 64, 25, 25) -> (B, 128, 25, 25)
        self.act2 = nn.SiLU()   
        self.pool2 = nn.MaxPool2d(kernel_size=2) # (B, 128, 25, 25) -> (B, 128, 12, 12)
        self.token_proj = nn.Linear(hidden_dim * 2, token_dim) #(B, 144, 128) -> (B, 144, 128)
        self.token_norm = nn.LayerNorm(token_dim)
        self.spatial_embedding = SpatialSinusoidalPositionEmbeddings2D(token_dim)



        # self.conv3 = nn.Conv2d(in_channels=hidden_dim * 2, out_channels=hidden_dim * 2, kernel_size=3, padding=1)
        # self.act3 = nn.SiLU()
        # self.pool3 = nn.AdaptiveAvgPool2d((12, 12))
        # self.flatten = nn.Flatten()
        # self.pos_mlp = nn.Sequential(
        #     nn.Linear(2, pos_hidden_dim),
        #     nn.SiLU(),
        #     nn.Linear(pos_hidden_dim, pos_hidden_dim),
        #     nn.SiLU(),
        # )
        # self.fc = nn.Sequential(
        #     nn.Linear(hidden_dim * 2 * 12 * 12 + pos_hidden_dim, 256),
        #     nn.SiLU(),
        #     nn.LayerNorm(256),
        #     nn.Linear(256, output_dim),
        # )

    def forward(self, x, current_position=None):
        x = self.pool1(self.act1(self.conv1(x)))
        x = self.pool2(self.act2(self.conv2(x)))

        _, _, height, width = x.shape
        map_tokens = torch.flatten(x, start_dim=2).transpose(1, 2)  # [B, Height*Width, channels]
        map_tokens = self.token_proj(map_tokens) # project to token_dim
        map_tokens = self.token_norm(map_tokens) # normalize across token_dim for each token
        map_tokens = map_tokens + self.spatial_embedding(
            height,
            width,
            device=map_tokens.device,
            dtype=map_tokens.dtype,
        ) # add spatial positional embedding to each token

        map_token_set.append(map_tokens.detach().cpu())

        return map_tokens



class SequenceSinusoidalPositionEmbeddings(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, length, device=None, dtype=None):
        device = device or torch.device("cpu")
        dtype = dtype or torch.float32

        pos = torch.linspace(-1.0, 1.0, length, device=device, dtype=dtype)

        half_dim = self.dim // 2
        omega = torch.arange(half_dim, device=device, dtype=dtype)
        omega = 1.0 / (10000 ** (omega / max(half_dim - 1, 1)))

        emb = pos[:, None] * omega[None, :]
        emb = torch.cat([emb.sin(), emb.cos()], dim=-1)

        if self.dim % 2 == 1:
            emb = F.pad(emb, (0, 1))

        return emb.unsqueeze(0)  # [1, length, D]



class SinusoidalTimestepEmbeddings(nn.Module):
    def __init__(self, dim):
        super().__init__()
        self.dim = dim

    def forward(self, time):
        device = time.device
        half_dim = self.dim // 2
        embeddings = math.log(10000) / max(half_dim - 1, 1)
        embeddings = torch.exp(torch.arange(half_dim, device=device) * -embeddings)
        embeddings = (time.float() / (T - 1))[:, None] * embeddings[None, :]
        embeddings = torch.cat((embeddings.sin(), embeddings.cos()), dim=-1)
        if self.dim % 2 == 1:
            embeddings = F.pad(embeddings, (0, 1))
        return embeddings
    

class WPTokenization(nn.Module):
    def __init__(self, token_dim):
        super().__init__()

        self.waypoint_proj = nn.Linear(2, token_dim)
        self.waypoint_pos_emb = SequenceSinusoidalPositionEmbeddings(token_dim)
        self.time_emb = SinusoidalTimestepEmbeddings(token_dim)
        self.time_mlp = nn.Sequential(
            nn.Linear(token_dim, token_dim),
            nn.SiLU(),
            nn.Linear(token_dim, token_dim),
            nn.SiLU(),
        )
        # self.final_norm = nn.LayerNorm(token_dim)
        self.current_pos_mlp = nn.Sequential(nn.Linear(2, token_dim), nn.SiLU(), nn.Linear(token_dim, token_dim))

    def forward(self, x, t, current_position): 
        """
        x: [B, 2, 8]
        returns: [B, 8, token_dim], one token per waypoint.
        """ 
        x = x.transpose(1, 2)  # [B, 8, 2]

        waypoint_tokens = self.waypoint_proj(x) # [B, 8, token_dim]
        waypoint_tokens = waypoint_tokens + self.waypoint_pos_emb(
            waypoint_tokens.shape[1],
            device=waypoint_tokens.device,
            dtype=waypoint_tokens.dtype,
        ) # add positional embedding to each waypoint token

        time_tokens = self.time_emb(t) # [B, token_dim]
        time_tokens = self.time_mlp(time_tokens) # [B, 1, token_dim]
        time_tokens = time_tokens.unsqueeze(1) # [B, 1, token_dim]

        current_pos_tokens = self.current_pos_mlp(current_position) # [B, token_dim]
        current_pos_tokens = current_pos_tokens.unsqueeze(1) # [B, 1, token_dim]

        waypoint_tokens = waypoint_tokens + time_tokens # add timestep embedding to each waypoint token
        waypoint_tokens = waypoint_tokens + current_pos_tokens # add current position embedding to each waypoint token

        # waypoint_tokens = self.final_norm(waypoint_tokens) # normalize across token_dim for each token
        
        return waypoint_tokens


class WPSelfAttention(nn.Module):
    def __init__(self, token_dim, num_heads=4, mlp_ratio=4, dropout=0.0):
        super().__init__()
        self.norm1 = nn.LayerNorm(token_dim)
        self.self_attn = nn.MultiheadAttention(
            embed_dim=token_dim,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True,
        )
        self.norm2 = nn.LayerNorm(token_dim)
        self.mlp = nn.Sequential(
            nn.Linear(token_dim, mlp_ratio * token_dim),
            nn.SiLU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_ratio * token_dim, token_dim),
            nn.Dropout(dropout),
        )



    def forward(self, waypoint_tokens):
        """
        waypoint_tokens: [B, 8, token_dim]
        returns: [B, 8, token_dim]
        """
        attn_input = self.norm1(waypoint_tokens)
        attn_out, _ = self.self_attn(attn_input, attn_input, attn_input, need_weights=False)
        waypoint_tokens = waypoint_tokens + attn_out

        mlp_input = self.norm2(waypoint_tokens)
        waypoint_tokens = waypoint_tokens + self.mlp(mlp_input)
        return waypoint_tokens


class WPMapCrossAttention(nn.Module):
    def __init__(self, token_dim, num_heads=4, mlp_ratio=4, dropout=0.0):
        super().__init__()
        self.wp_norm = nn.LayerNorm(token_dim)
        self.map_norm = nn.LayerNorm(token_dim)
        self.cross_attn = nn.MultiheadAttention(
            embed_dim=token_dim,
            num_heads=num_heads,
            dropout=dropout,
            batch_first=True,
        )
        self.norm2 = nn.LayerNorm(token_dim)
        self.mlp = nn.Sequential(
            nn.Linear(token_dim, mlp_ratio * token_dim),
            nn.SiLU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_ratio * token_dim, token_dim),
            nn.Dropout(dropout),
        )

    def forward(self, waypoint_tokens, map_tokens):
        """
        waypoint_tokens: [B, 8, token_dim]
        map_tokens: [B, H*W, token_dim], currently [B, 144, token_dim]
        returns: [B, 8, token_dim]
        """
        query = self.wp_norm(waypoint_tokens)
        key_value = self.map_norm(map_tokens)
        attn_out, _ = self.cross_attn(
            query=query,
            key=key_value,
            value=key_value,
            need_weights=False,
        )
        waypoint_tokens = waypoint_tokens + attn_out

        mlp_input = self.norm2(waypoint_tokens)
        waypoint_tokens = waypoint_tokens + self.mlp(mlp_input)
        return waypoint_tokens







# Class ConditionalResBlock1D(nn.Module):
#     def __init__(self, in_channels, out_channels, cond_dim, groups=8):
#         super().__init__()
#         self.conv1 = nn.Conv1d(in_channels, out_channels, kernel_size=3, padding=1)
#         self.norm1 = nn.GroupNorm(groups, out_channels)
#         self.conv2 = nn.Conv1d(out_channels, out_channels, kernel_size=3, padding=1)
#         self.norm2 = nn.GroupNorm(groups, out_channels)
#         self.cond_layer = nn.Linear(cond_dim, out_channels * 2)
#         self.act = nn.SiLU()
#         self.residual = (
#             nn.Conv1d(in_channels, out_channels, kernel_size=1)
#             if in_channels != out_channels
#             else nn.Identity()
#         )

#     def forward(self, x, cond):
#         residual = self.residual(x)

#         x = self.conv1(x)
#         x = self.norm1(x)
#         x = self.act(x)

#         gamma, beta = self.cond_layer(cond).chunk(2, dim=-1)
#         x = (1.0 + gamma[:, :, None]) * x + beta[:, :, None]

#         x = self.conv2(x)
#         x = self.norm2(x)
#         x = self.act(x)

#         return x + residual


class NoisePredictor(nn.Module):
    def __init__(self, time_emb_dim=64, token_dim=256, base_channels=64):
        super().__init__()
        self.mean_var_marker_cnn = MeanVarMarkerCNN(input_channels=3, hidden_dim=base_channels, token_dim=token_dim)
        self.wp_tokenization = WPTokenization(token_dim)
        self.wpself_attn = WPSelfAttention(token_dim)
        self.wpmap_cross_attn = WPMapCrossAttention(token_dim)


        self.output = nn.Linear(token_dim, 2)


    def forward(self, x, t, meanvarmarker_map, current_position=None):
        map_tokens = self.mean_var_marker_cnn(meanvarmarker_map) # [B, 144, token_dim]
        wp_tokens = self.wp_tokenization(x, t, current_position) # [B, 8, token_dim]
        wp_tokens = self.wpself_attn(wp_tokens) # [B, 8, token_dim]
        wp_tokens = self.wpmap_cross_attn(wp_tokens, map_tokens) # [B, 8, token_dim]
        noise_pred = self.output(wp_tokens) # [B, 8, 2]
        return noise_pred.transpose(1, 2) # [B, 2, 8]
        


model = NoisePredictor().to(device)
optimizer = AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)


def remap_legacy_state_dict_keys(state_dict):
    remapped = {}
    old_prefix = "mean_var_cnn."
    new_prefix = "mean_var_marker_cnn."
    for key, value in state_dict.items():
        if key.startswith(old_prefix):
            key = new_prefix + key[len(old_prefix):]
        remapped[key] = value
    return remapped



def get_loss(model, x_0, t, meanvarmarker_map, current_position, weights, alpha=0.1):
    waypoints_noisy, noise = forward_diffusion_sample(x_0, t) 
    with torch.autocast(
        device_type="cuda",
        dtype=torch.bfloat16,
        enabled=waypoints_noisy.is_cuda,
    ):
        noise_pred = model(waypoints_noisy, t, meanvarmarker_map, current_position)
    noise_pred = noise_pred.float()

    waypoint_loss = (noise_pred - noise).pow(2).mean(dim=[1, 2])


    # traj_noise_pred = pytorch_cubic_spline(noise_pred, current_position)
    # traj_noise_true = pytorch_cubic_spline(noise, current_position)


    # spline_loss = (traj_noise_pred - traj_noise_true).pow(2).mean(dim=[1, 2])

    # per_sample_loss = waypoint_loss + alpha * spline_loss
    per_sample_loss = waypoint_loss
    return (per_sample_loss * weights).sum() / (weights.sum() + 1e-6)


# @torch.no_grad()
# def sample_timestep(x, t, meanvar_map, current_position):
#     betas_t = get_index_from_list(betas, t, x.shape)
#     sqrt_one_minus_alphas_cumprod_t = get_index_from_list(sqrt_one_minus_alphas_cumprod, t, x.shape)
#     sqrt_recip_alphas_t = get_index_from_list(sqrt_recip_alphas, t, x.shape)
#
#     model_mean = sqrt_recip_alphas_t * (
#         x - betas_t * model(x, t, meanvar_map, current_position) / sqrt_one_minus_alphas_cumprod_t
#     )
#     posterior_variance_t = get_index_from_list(posterior_variance, t, x.shape)
#
#     if t[0].item() == 0:
#         return model_mean
#
#     noise = torch.randn_like(x)
#     return model_mean + torch.sqrt(posterior_variance_t) * noise


@torch.no_grad()
def ddim_sample_timestep(x, t, t_prev, meanvarmarker_map, current_position, clip_x0=False):
    if meanvarmarker_map.shape[1] != 3:
        raise ValueError(
            f"Expected meanvarmarker_map with 3 channels, got {tuple(meanvarmarker_map.shape)}"
        )
    alpha_bar_t = get_index_from_list(alphas_cumprod, t, x.shape)
    sqrt_alpha_bar_t = torch.sqrt(alpha_bar_t)
    sqrt_one_minus_alpha_bar_t = torch.sqrt(1.0 - alpha_bar_t)

    noise_pred = model(x, t, meanvarmarker_map, current_position)
    x0_pred = (x - sqrt_one_minus_alpha_bar_t * noise_pred) / sqrt_alpha_bar_t
    if clip_x0:
        x0_pred = x0_pred.clamp(-1.0, 1.0)

    if t_prev[0].item() < 0:
        return x0_pred

    alpha_bar_prev = get_index_from_list(alphas_cumprod, t_prev, x.shape)
    sqrt_alpha_bar_prev = torch.sqrt(alpha_bar_prev)
    sqrt_one_minus_alpha_bar_prev = torch.sqrt(1.0 - alpha_bar_prev)

    x_prev = sqrt_alpha_bar_prev * x0_pred + sqrt_one_minus_alpha_bar_prev * noise_pred
    return x_prev

@torch.no_grad()
def ddim_sample(initial_noise, meanvarmarker_map, current_position, num_steps=None, clip_x0=False):
    if meanvarmarker_map.shape[1] != 3:
        raise ValueError(
            f"Expected meanvarmarker_map with 3 channels, got {tuple(meanvarmarker_map.shape)}"
        )
    x = initial_noise
    if num_steps is None or num_steps >= T:
        schedule = list(range(T - 1, -1, -1))
    else:
        schedule = torch.linspace(T - 1, 0, steps=num_steps, device=x.device).long().unique_consecutive().tolist()

    for step_idx, i in enumerate(schedule):
        prev_i = schedule[step_idx + 1] if step_idx + 1 < len(schedule) else -1
        t = torch.full((x.shape[0],), i, dtype=torch.long, device=x.device)
        t_prev = torch.full((x.shape[0],), prev_i, dtype=torch.long, device=x.device)
        x = ddim_sample_timestep(x, t, t_prev, meanvarmarker_map, current_position, clip_x0=clip_x0)
    return x


@torch.no_grad()
def sample_plot_traj(output_path=None):
    model.eval()
    traj = torch.randn((1, *TARGET_SHAPE), device=next(model.parameters()).device)
    meanvarmarker_map = meanvarmarkermaps[0:1].to(next(model.parameters()).device)
    current_position = conditions[0:1].to(next(model.parameters()).device)
    plt.figure(figsize=(6, 6))
    plt.axis("equal")
    plt.grid(True)

    traj = ddim_sample(traj, meanvarmarker_map, current_position)

    traj_to_plot = extract_control_waypoints(traj[0].cpu())
    #.clamp(0.0, SCALE_FACTOR)
    truth_to_plot = extract_control_waypoints(trajectories[0].cpu())
    plt.plot(traj_to_plot[0], traj_to_plot[1], marker="o", label="Generated control waypoints")
    plt.plot(truth_to_plot[0], truth_to_plot[1], marker="x", label="Ground truth control waypoints")
    plt.legend()
    if output_path is None:
        output_path = PLOT_DIR / "sparse_sample_plot.png"
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved sample plot to {output_path}")



def train_one_sample(model, steps=3000, batch_size=64):
    losses = []
    optimizer = AdamW(model.parameters(), lr=1e-3, weight_decay=0.0)
    model.train()

    x0 = trajectories[:1].to(device)
    pos0 = conditions[:1].to(device)
    meanvarmarker_map = meanvarmarkermaps[:1].to(device)

    for step in range(steps):
        traj = x0.repeat(batch_size, 1, 1)
        current_position = pos0.repeat(batch_size, 1)
        batch_meanvarmarker_map = meanvarmarker_map.repeat(batch_size, 1, 1, 1)
        batch_weights = torch.ones(batch_size, device=device)

        t = torch.randint(0, T, (batch_size,), device=device).long()
        loss = get_loss(model, traj, t, batch_meanvarmarker_map, current_position, weights=batch_weights)
        losses.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if step % 100 == 0:
            print(f"step {step}, loss {loss.item():.4f}")

    final_path = CHECKPOINT_DIR / "sparse_control_one_sample_final.pth"
    torch.save(model.state_dict(), final_path)
    print(f"Saved one-sample model to {final_path}")

    plt.figure()
    plt.plot(losses)
    plt.xlabel("Step")
    plt.ylabel("Loss")
    plt.title("One-sample SD-DA MLP diffusion loss")
    loss_plot_path = PLOT_DIR / "sparse_one_sample_loss.png"
    plt.savefig(loss_plot_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved one-sample loss plot to {loss_plot_path}")

    sample_plot_traj(PLOT_DIR / "sparse_one_sample_sample.png")
    return losses


@torch.no_grad()
def evaluate(model, dataloader):
    was_training = model.training
    model.eval()
    weighted_loss_sum = 0.0
    total_weight = 0.0
    model_device = next(model.parameters()).device

    for batch in dataloader:
        traj, current_position, meanvarmarker_map, batch_weights = batch
        traj = traj.to(model_device, non_blocking=True)
        current_position = current_position.to(model_device, non_blocking=True)
        meanvarmarker_map = meanvarmarker_map.to(model_device, non_blocking=True)
        batch_weights = batch_weights.to(model_device, non_blocking=True)
        t = torch.randint(0, T, (traj.shape[0],), device=traj.device).long()
        loss = get_loss(model, traj, t, meanvarmarker_map, current_position, weights=batch_weights)
        batch_weight_sum = batch_weights.sum().item()
        weighted_loss_sum += loss.item() * batch_weight_sum
        total_weight += batch_weight_sum

    if was_training:
        model.train()

    if total_weight <= 0.0:
        return float("nan")
    return weighted_loss_sum / total_weight


def train(
    model,
    dataloader,
    epochs,
    betas=betas,
    lr=1e-3,
    save_every=100,
    val_dataloader=None,
):
    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=0.0)
    model.train()
    loss_vals = []
    stepcount = []
    val_loss_vals = []
    val_steps = []

    for epoch in range(epochs):
        print(f"Epoch {epoch + 1}/{epochs}")
        for step, batch in tqdm(enumerate(dataloader), total=len(dataloader)):
            stepcount.append(epoch * len(dataloader) + step)
            traj, current_position, meanvarmarker_map, batch_weights = batch
            model_device = next(model.parameters()).device
            traj = traj.to(model_device, non_blocking=True)
            current_position = current_position.to(model_device, non_blocking=True)
            meanvarmarker_map = meanvarmarker_map.to(model_device, non_blocking=True)
            batch_weights = batch_weights.to(model_device, non_blocking=True)
            batch_size = traj.shape[0]
            t = torch.randint(0, T, (batch_size,), device=traj.device).long()
            loss = get_loss(model, traj, t, meanvarmarker_map, current_position, weights=batch_weights)
            loss_vals.append(loss.item())

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            if step % 100 == 0:
                print(f"Step {step}, Loss: {loss.item():.4f}", flush=True)

        if (epoch + 1) % save_every == 0:
            checkpoint = {
                "epoch": epoch + 1,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "loss": loss.item(),
            }
            checkpoint_path = CHECKPOINT_DIR / f"sparse_trans_waypoints_epoch_{epoch + 1}.pth"
            torch.save(checkpoint, checkpoint_path)
            print(f"Checkpoint saved: {checkpoint_path}")

        if val_dataloader is not None:
            val_loss = evaluate(model, val_dataloader)
            val_loss_vals.append(val_loss)
            val_steps.append((epoch + 1) * len(dataloader))
            print(f"Epoch {epoch + 1} held-out validation loss: {val_loss:.6f}", flush=True)

        print(f"Epoch {epoch + 1} complete, lr={lr:.6f}", flush=True)
    
    window = min(200, len(loss_vals))
    plt.figure()
    if window > 1:
        kernel = np.ones(window, dtype=np.float32) / window
        moving_avg = np.convolve(np.asarray(loss_vals, dtype=np.float32), kernel, mode="valid")
        moving_avg_steps = stepcount[window - 1:]
        plt.plot(stepcount, loss_vals, alpha=0.18, label="Raw Training Loss")
        plt.plot(moving_avg_steps, moving_avg, label=f"{window}-Step Moving Average")
    else:
        plt.plot(stepcount, loss_vals, label="Training Loss")
    plt.xlabel("Step")
    plt.ylabel("Loss")
    plt.title("SparseTrans Diffusion Training Loss")
    plt.legend()
    loss_plot_path = PLOT_DIR / "sparse_trans_training_loss.png"
    plt.savefig(loss_plot_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Saved training loss plot to {loss_plot_path}")

    if val_loss_vals:
        plt.figure()
        plt.plot(
            val_steps,
            val_loss_vals,
            marker="o",
            label="Held-Out Validation Loss",
        )
        plt.xlabel("Training Step")
        plt.ylabel("Loss")
        plt.title("SparseTrans Diffusion Held-Out Validation Loss")
        plt.legend()
        val_loss_plot_path = PLOT_DIR / "sparse_trans_validation_loss.png"
        plt.savefig(val_loss_plot_path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"Saved validation loss plot to {val_loss_plot_path}")

    sample_plot_traj(PLOT_DIR / "sparse_trans_training_sample.png")


   


if __name__ == "__main__":
    print("Checkpoint directory made", flush=True)
    print("Using device:", device, flush=True)

    print("Building SparseTrans diffusion model", flush=True)
    model = NoisePredictor().to(device)

    # print("Training one-sample overfit model", flush=True)
    #batch_weights = torch.ones(batch_size, device=device)
    # train_one_sample(model, steps=EPOCHS, batch_size=BATCH_SIZE)
    dataloader_kwargs = {
        "batch_size": BATCH_SIZE,
        "shuffle": True,
        "num_workers": 4 if torch.cuda.is_available() else 0,
        "pin_memory": torch.cuda.is_available(),
    }
    if dataloader_kwargs["num_workers"] > 0:
        dataloader_kwargs["persistent_workers"] = True

    train_mask, val_mask, val_map_ids = build_map_id_split(val_count=2)
    print(f"Validation map_ids: {val_map_ids.tolist()}", flush=True)
    print(f"Training samples: {int(train_mask.sum().item())}", flush=True)
    print(f"Validation samples: {int(val_mask.sum().item())}", flush=True)

    train_dataset = TrajectoryDataset(
        trajectories[train_mask],
        weights[train_mask],
        meanvarmarkermaps=meanvarmarkermaps[train_mask],
        conditions=conditions[train_mask],
    )
    val_dataset = TrajectoryDataset(
        trajectories[val_mask],
        weights[val_mask],
        meanvarmarkermaps=meanvarmarkermaps[val_mask],
        conditions=conditions[val_mask],
    )
    val_dataloader_kwargs = dict(dataloader_kwargs)
    val_dataloader_kwargs["shuffle"] = False

    print("Starting training loop", flush=True)

    train(
        model,
        DataLoader(train_dataset, **dataloader_kwargs),
        epochs=EPOCHS,
        val_dataloader=DataLoader(val_dataset, **val_dataloader_kwargs),
    )

    print("Done training", flush=True)

    print("control_waypoints shape:", control_waypoints.shape, flush=True)

   
# # run model/sample/training batch here so map_token_set gets populated

#     plot_captured_map_tokens(
#         max_sets=4,
#         sample_index=0,
#         channel_indices=(0, 1, 2),
#     )   

    

